/*
 * This file is generated by jOOQ.
*/
package com.twitchexplorer.twitchexplorer.model.pojo;


import java.io.Serializable;


@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class BroadcasterType implements Serializable {

    private static final long serialVersionUID = 309927328;

    private final Integer broadcasterTypeId;
    private final String type;

    public BroadcasterType(BroadcasterType value) {
        this.broadcasterTypeId = value.broadcasterTypeId;
        this.type = value.type;
    }

    public BroadcasterType(
            Integer broadcasterTypeId,
            String type
    ) {
        this.broadcasterTypeId = broadcasterTypeId;
        this.type = type;
    }

    public Integer getBroadcasterTypeId() {
        return this.broadcasterTypeId;
    }

    public String getType() {
        return this.type;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BroadcasterType (");

        sb.append(broadcasterTypeId);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
