/*
 * This file is generated by jOOQ.
*/
package com.twitchexplorer.twitchexplorer.model.pojo;


import java.io.Serializable;


@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class GamesLive implements Serializable {

    private static final long serialVersionUID = 129325213;

    private final Integer gameId;
    private final String name;
    private final String artUrl;

    public GamesLive(GamesLive value) {
        this.gameId = value.gameId;
        this.name = value.name;
        this.artUrl = value.artUrl;
    }

    public GamesLive(
            Integer gameId,
            String name,
            String artUrl
    ) {
        this.gameId = gameId;
        this.name = name;
        this.artUrl = artUrl;
    }

    public Integer getGameId() {
        return this.gameId;
    }

    public String getName() {
        return this.name;
    }

    public String getArtUrl() {
        return this.artUrl;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GamesLive (");

        sb.append(gameId);
        sb.append(", ").append(name);
        sb.append(", ").append(artUrl);

        sb.append(")");
        return sb.toString();
    }
}
