/*
 * This file is generated by jOOQ.
*/
package com.twitchexplorer.twitchexplorer.model.pojo;


import java.io.Serializable;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StreamType implements Serializable {

    private static final long serialVersionUID = -976411473;

    private final Integer streamTypeId;
    private final String  name;

    public StreamType(StreamType value) {
        this.streamTypeId = value.streamTypeId;
        this.name = value.name;
    }

    public StreamType(
        Integer streamTypeId,
        String  name
    ) {
        this.streamTypeId = streamTypeId;
        this.name = name;
    }

    public Integer getStreamTypeId() {
        return this.streamTypeId;
    }

    public String getName() {
        return this.name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StreamType (");

        sb.append(streamTypeId);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
