/*
 * This file is generated by jOOQ.
*/
package com.twitchexplorer.twitchexplorer.model.pojo;


import java.io.Serializable;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserType implements Serializable {

    private static final long serialVersionUID = -1824335874;

    private final Integer userTypeId;
    private final String  type;

    public UserType(UserType value) {
        this.userTypeId = value.userTypeId;
        this.type = value.type;
    }

    public UserType(
        Integer userTypeId,
        String  type
    ) {
        this.userTypeId = userTypeId;
        this.type = type;
    }

    public Integer getUserTypeId() {
        return this.userTypeId;
    }

    public String getType() {
        return this.type;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserType (");

        sb.append(userTypeId);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
