/*
 * This file is generated by jOOQ.
*/
package twitch.explorer.database.jooq.db;


import javax.annotation.Generated;

import twitch.explorer.database.jooq.db.tables.BroadcasterType;
import twitch.explorer.database.jooq.db.tables.Client;
import twitch.explorer.database.jooq.db.tables.Community;
import twitch.explorer.database.jooq.db.tables.Followers;
import twitch.explorer.database.jooq.db.tables.Game;
import twitch.explorer.database.jooq.db.tables.GamesLive;
import twitch.explorer.database.jooq.db.tables.Language;
import twitch.explorer.database.jooq.db.tables.LatestFollowersUpdateView;
import twitch.explorer.database.jooq.db.tables.LiveLongestTimeSinceFollowerUpdateView;
import twitch.explorer.database.jooq.db.tables.LiveStreamsView;
import twitch.explorer.database.jooq.db.tables.NewView;
import twitch.explorer.database.jooq.db.tables.Stream;
import twitch.explorer.database.jooq.db.tables.StreamCommunity;
import twitch.explorer.database.jooq.db.tables.StreamType;
import twitch.explorer.database.jooq.db.tables.User;
import twitch.explorer.database.jooq.db.tables.UserType;
import twitch.explorer.database.jooq.db.tables.Vote;


/**
 * Convenience access to all tables in twitch
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * more info at: https://dev.twitch.tv/docs/api/reference#get-users
User’s broadcaster type: "partner", "affiliate", or "".
     */
    public static final BroadcasterType BROADCASTER_TYPE = twitch.explorer.database.jooq.db.tables.BroadcasterType.BROADCASTER_TYPE;

    /**
     * The table <code>twitch.client</code>.
     */
    public static final Client CLIENT = twitch.explorer.database.jooq.db.tables.Client.CLIENT;

    /**
     * The table <code>twitch.community</code>.
     */
    public static final Community COMMUNITY = twitch.explorer.database.jooq.db.tables.Community.COMMUNITY;

    /**
     * The table <code>twitch.followers</code>.
     */
    public static final Followers FOLLOWERS = twitch.explorer.database.jooq.db.tables.Followers.FOLLOWERS;

    /**
     * The table <code>twitch.game</code>.
     */
    public static final Game GAME = twitch.explorer.database.jooq.db.tables.Game.GAME;

    /**
     * VIEW
     */
    public static final GamesLive GAMES_LIVE = twitch.explorer.database.jooq.db.tables.GamesLive.GAMES_LIVE;

    /**
     * The table <code>twitch.language</code>.
     */
    public static final Language LANGUAGE = twitch.explorer.database.jooq.db.tables.Language.LANGUAGE;

    /**
     * VIEW
     */
    public static final LatestFollowersUpdateView LATEST_FOLLOWERS_UPDATE_VIEW = twitch.explorer.database.jooq.db.tables.LatestFollowersUpdateView.LATEST_FOLLOWERS_UPDATE_VIEW;

    /**
     * VIEW
     */
    public static final LiveLongestTimeSinceFollowerUpdateView LIVE_LONGEST_TIME_SINCE_FOLLOWER_UPDATE_VIEW = twitch.explorer.database.jooq.db.tables.LiveLongestTimeSinceFollowerUpdateView.LIVE_LONGEST_TIME_SINCE_FOLLOWER_UPDATE_VIEW;

    /**
     * VIEW
     */
    public static final LiveStreamsView LIVE_STREAMS_VIEW = twitch.explorer.database.jooq.db.tables.LiveStreamsView.LIVE_STREAMS_VIEW;

    /**
     * VIEW
     */
    public static final NewView NEW_VIEW = twitch.explorer.database.jooq.db.tables.NewView.NEW_VIEW;

    /**
     * The table <code>twitch.stream</code>.
     */
    public static final Stream STREAM = twitch.explorer.database.jooq.db.tables.Stream.STREAM;

    /**
     * The table <code>twitch.stream_community</code>.
     */
    public static final StreamCommunity STREAM_COMMUNITY = twitch.explorer.database.jooq.db.tables.StreamCommunity.STREAM_COMMUNITY;

    /**
     * The table <code>twitch.stream_type</code>.
     */
    public static final StreamType STREAM_TYPE = twitch.explorer.database.jooq.db.tables.StreamType.STREAM_TYPE;

    /**
     * The table <code>twitch.user</code>.
     */
    public static final User USER = twitch.explorer.database.jooq.db.tables.User.USER;

    /**
     * The table <code>twitch.user_type</code>.
     */
    public static final UserType USER_TYPE = twitch.explorer.database.jooq.db.tables.UserType.USER_TYPE;

    /**
     * The table <code>twitch.vote</code>.
     */
    public static final Vote VOTE = twitch.explorer.database.jooq.db.tables.Vote.VOTE;
}
