/*
 * This file is generated by jOOQ.
*/
package twitch.explorer.database.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import twitch.explorer.database.jooq.db.Indexes;
import twitch.explorer.database.jooq.db.Keys;
import twitch.explorer.database.jooq.db.Twitch;
import twitch.explorer.database.jooq.db.tables.records.CommunityRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Community extends TableImpl<CommunityRecord> {

    private static final long serialVersionUID = -1366843193;

    /**
     * The reference instance of <code>twitch.community</code>
     */
    public static final Community COMMUNITY = new Community();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CommunityRecord> getRecordType() {
        return CommunityRecord.class;
    }

    /**
     * The column <code>twitch.community.community_id</code>.
     */
    public final TableField<CommunityRecord, Integer> COMMUNITY_ID = createField("community_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>twitch.community.name</code>.
     */
    public final TableField<CommunityRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * Create a <code>twitch.community</code> table reference
     */
    public Community() {
        this(DSL.name("community"), null);
    }

    /**
     * Create an aliased <code>twitch.community</code> table reference
     */
    public Community(String alias) {
        this(DSL.name(alias), COMMUNITY);
    }

    /**
     * Create an aliased <code>twitch.community</code> table reference
     */
    public Community(Name alias) {
        this(alias, COMMUNITY);
    }

    private Community(Name alias, Table<CommunityRecord> aliased) {
        this(alias, aliased, null);
    }

    private Community(Name alias, Table<CommunityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Twitch.TWITCH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.COMMUNITY_NAME_UNIQUE, Indexes.COMMUNITY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CommunityRecord, Integer> getIdentity() {
        return Keys.IDENTITY_COMMUNITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CommunityRecord> getPrimaryKey() {
        return Keys.KEY_COMMUNITY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CommunityRecord>> getKeys() {
        return Arrays.<UniqueKey<CommunityRecord>>asList(Keys.KEY_COMMUNITY_PRIMARY, Keys.KEY_COMMUNITY_NAME_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Community as(String alias) {
        return new Community(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Community as(Name alias) {
        return new Community(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Community rename(String name) {
        return new Community(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Community rename(Name name) {
        return new Community(name, null);
    }
}
