/*
 * This file is generated by jOOQ.
*/
package twitch.explorer.database.jooq.db.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import twitch.explorer.database.jooq.db.Twitch;
import twitch.explorer.database.jooq.db.tables.records.GamesLiveRecord;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GamesLive extends TableImpl<GamesLiveRecord> {

    private static final long serialVersionUID = 972516101;

    /**
     * The reference instance of <code>twitch.games_live</code>
     */
    public static final GamesLive GAMES_LIVE = new GamesLive();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GamesLiveRecord> getRecordType() {
        return GamesLiveRecord.class;
    }

    /**
     * The column <code>twitch.games_live.game_id</code>.
     */
    public final TableField<GamesLiveRecord, Integer> GAME_ID = createField("game_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>twitch.games_live.name</code>.
     */
    public final TableField<GamesLiveRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>twitch.games_live.art_url</code>.
     */
    public final TableField<GamesLiveRecord, String> ART_URL = createField("art_url", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>twitch.games_live</code> table reference
     */
    public GamesLive() {
        this(DSL.name("games_live"), null);
    }

    /**
     * Create an aliased <code>twitch.games_live</code> table reference
     */
    public GamesLive(String alias) {
        this(DSL.name(alias), GAMES_LIVE);
    }

    /**
     * Create an aliased <code>twitch.games_live</code> table reference
     */
    public GamesLive(Name alias) {
        this(alias, GAMES_LIVE);
    }

    private GamesLive(Name alias, Table<GamesLiveRecord> aliased) {
        this(alias, aliased, null);
    }

    private GamesLive(Name alias, Table<GamesLiveRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "VIEW");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Twitch.TWITCH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GamesLive as(String alias) {
        return new GamesLive(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GamesLive as(Name alias) {
        return new GamesLive(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GamesLive rename(String name) {
        return new GamesLive(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GamesLive rename(Name name) {
        return new GamesLive(name, null);
    }
}
