/*
 * This file is generated by jOOQ.
*/
package twitch.explorer.database.jooq.db.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import twitch.explorer.database.jooq.db.Twitch;
import twitch.explorer.database.jooq.db.tables.records.LatestFollowersUpdateViewRecord;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LatestFollowersUpdateView extends TableImpl<LatestFollowersUpdateViewRecord> {

    private static final long serialVersionUID = -1797160374;

    /**
     * The reference instance of <code>twitch.latest_followers_update_view</code>
     */
    public static final LatestFollowersUpdateView LATEST_FOLLOWERS_UPDATE_VIEW = new LatestFollowersUpdateView();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LatestFollowersUpdateViewRecord> getRecordType() {
        return LatestFollowersUpdateViewRecord.class;
    }

    /**
     * The column <code>twitch.latest_followers_update_view.followers_id</code>.
     */
    public final TableField<LatestFollowersUpdateViewRecord, Integer> FOLLOWERS_ID = createField("followers_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>twitch.latest_followers_update_view.followers</code>.
     */
    public final TableField<LatestFollowersUpdateViewRecord, Integer> FOLLOWERS = createField("followers", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>twitch.latest_followers_update_view.fetched</code>.
     */
    public final TableField<LatestFollowersUpdateViewRecord, Timestamp> FETCHED = createField("fetched", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>twitch.latest_followers_update_view.user_id</code>.
     */
    public final TableField<LatestFollowersUpdateViewRecord, Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>twitch.latest_followers_update_view</code> table reference
     */
    public LatestFollowersUpdateView() {
        this(DSL.name("latest_followers_update_view"), null);
    }

    /**
     * Create an aliased <code>twitch.latest_followers_update_view</code> table reference
     */
    public LatestFollowersUpdateView(String alias) {
        this(DSL.name(alias), LATEST_FOLLOWERS_UPDATE_VIEW);
    }

    /**
     * Create an aliased <code>twitch.latest_followers_update_view</code> table reference
     */
    public LatestFollowersUpdateView(Name alias) {
        this(alias, LATEST_FOLLOWERS_UPDATE_VIEW);
    }

    private LatestFollowersUpdateView(Name alias, Table<LatestFollowersUpdateViewRecord> aliased) {
        this(alias, aliased, null);
    }

    private LatestFollowersUpdateView(Name alias, Table<LatestFollowersUpdateViewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "VIEW");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Twitch.TWITCH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LatestFollowersUpdateView as(String alias) {
        return new LatestFollowersUpdateView(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LatestFollowersUpdateView as(Name alias) {
        return new LatestFollowersUpdateView(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public LatestFollowersUpdateView rename(String name) {
        return new LatestFollowersUpdateView(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LatestFollowersUpdateView rename(Name name) {
        return new LatestFollowersUpdateView(name, null);
    }
}
