/*
 * This file is generated by jOOQ.
*/
package twitch.explorer.database.jooq.db.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import twitch.explorer.database.jooq.db.Twitch;
import twitch.explorer.database.jooq.db.tables.records.LiveLongestTimeSinceFollowerUpdateViewRecord;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LiveLongestTimeSinceFollowerUpdateView extends TableImpl<LiveLongestTimeSinceFollowerUpdateViewRecord> {

    private static final long serialVersionUID = -2134298740;

    /**
     * The reference instance of <code>twitch.live_longest_time_since_follower_update_view</code>
     */
    public static final LiveLongestTimeSinceFollowerUpdateView LIVE_LONGEST_TIME_SINCE_FOLLOWER_UPDATE_VIEW = new LiveLongestTimeSinceFollowerUpdateView();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LiveLongestTimeSinceFollowerUpdateViewRecord> getRecordType() {
        return LiveLongestTimeSinceFollowerUpdateViewRecord.class;
    }

    /**
     * The column <code>twitch.live_longest_time_since_follower_update_view.stream_id</code>.
     */
    public final TableField<LiveLongestTimeSinceFollowerUpdateViewRecord, Long> STREAM_ID = createField("stream_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>twitch.live_longest_time_since_follower_update_view.title</code>.
     */
    public final TableField<LiveLongestTimeSinceFollowerUpdateViewRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>twitch.live_longest_time_since_follower_update_view.started</code>.
     */
    public final TableField<LiveLongestTimeSinceFollowerUpdateViewRecord, Timestamp> STARTED = createField("started", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>twitch.live_longest_time_since_follower_update_view.thumbnail</code>.
     */
    public final TableField<LiveLongestTimeSinceFollowerUpdateViewRecord, String> THUMBNAIL = createField("thumbnail", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>twitch.live_longest_time_since_follower_update_view.view_count</code>. latest read view count
     */
    public final TableField<LiveLongestTimeSinceFollowerUpdateViewRecord, Integer> VIEW_COUNT = createField("view_count", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "latest read view count");

    /**
     * The column <code>twitch.live_longest_time_since_follower_update_view.user_id</code>.
     */
    public final TableField<LiveLongestTimeSinceFollowerUpdateViewRecord, Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>twitch.live_longest_time_since_follower_update_view.game_id</code>.
     */
    public final TableField<LiveLongestTimeSinceFollowerUpdateViewRecord, Integer> GAME_ID = createField("game_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>twitch.live_longest_time_since_follower_update_view.followers</code>.
     */
    public final TableField<LiveLongestTimeSinceFollowerUpdateViewRecord, Integer> FOLLOWERS = createField("followers", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>twitch.live_longest_time_since_follower_update_view.fetched</code>.
     */
    public final TableField<LiveLongestTimeSinceFollowerUpdateViewRecord, Timestamp> FETCHED = createField("fetched", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>twitch.live_longest_time_since_follower_update_view</code> table reference
     */
    public LiveLongestTimeSinceFollowerUpdateView() {
        this(DSL.name("live_longest_time_since_follower_update_view"), null);
    }

    /**
     * Create an aliased <code>twitch.live_longest_time_since_follower_update_view</code> table reference
     */
    public LiveLongestTimeSinceFollowerUpdateView(String alias) {
        this(DSL.name(alias), LIVE_LONGEST_TIME_SINCE_FOLLOWER_UPDATE_VIEW);
    }

    /**
     * Create an aliased <code>twitch.live_longest_time_since_follower_update_view</code> table reference
     */
    public LiveLongestTimeSinceFollowerUpdateView(Name alias) {
        this(alias, LIVE_LONGEST_TIME_SINCE_FOLLOWER_UPDATE_VIEW);
    }

    private LiveLongestTimeSinceFollowerUpdateView(Name alias, Table<LiveLongestTimeSinceFollowerUpdateViewRecord> aliased) {
        this(alias, aliased, null);
    }

    private LiveLongestTimeSinceFollowerUpdateView(Name alias, Table<LiveLongestTimeSinceFollowerUpdateViewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "VIEW");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Twitch.TWITCH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveLongestTimeSinceFollowerUpdateView as(String alias) {
        return new LiveLongestTimeSinceFollowerUpdateView(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveLongestTimeSinceFollowerUpdateView as(Name alias) {
        return new LiveLongestTimeSinceFollowerUpdateView(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public LiveLongestTimeSinceFollowerUpdateView rename(String name) {
        return new LiveLongestTimeSinceFollowerUpdateView(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LiveLongestTimeSinceFollowerUpdateView rename(Name name) {
        return new LiveLongestTimeSinceFollowerUpdateView(name, null);
    }
}
