/*
 * This file is generated by jOOQ.
*/
package twitch.explorer.database.jooq.db.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import twitch.explorer.database.jooq.db.Twitch;
import twitch.explorer.database.jooq.db.tables.records.LiveStreamsViewRecord;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LiveStreamsView extends TableImpl<LiveStreamsViewRecord> {

    private static final long serialVersionUID = 770226408;

    /**
     * The reference instance of <code>twitch.live_streams_view</code>
     */
    public static final LiveStreamsView LIVE_STREAMS_VIEW = new LiveStreamsView();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LiveStreamsViewRecord> getRecordType() {
        return LiveStreamsViewRecord.class;
    }

    /**
     * The column <code>twitch.live_streams_view.stream_id</code>.
     */
    public final TableField<LiveStreamsViewRecord, Long> STREAM_ID = createField("stream_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>twitch.live_streams_view.title</code>.
     */
    public final TableField<LiveStreamsViewRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>twitch.live_streams_view.started</code>.
     */
    public final TableField<LiveStreamsViewRecord, Timestamp> STARTED = createField("started", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>twitch.live_streams_view.ended</code>.
     */
    public final TableField<LiveStreamsViewRecord, Timestamp> ENDED = createField("ended", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>twitch.live_streams_view.thumbnail</code>.
     */
    public final TableField<LiveStreamsViewRecord, String> THUMBNAIL = createField("thumbnail", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>twitch.live_streams_view.view_count</code>. latest read view count
     */
    public final TableField<LiveStreamsViewRecord, Integer> VIEW_COUNT = createField("view_count", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "latest read view count");

    /**
     * The column <code>twitch.live_streams_view.user_id</code>.
     */
    public final TableField<LiveStreamsViewRecord, Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>twitch.live_streams_view.game_id</code>.
     */
    public final TableField<LiveStreamsViewRecord, Integer> GAME_ID = createField("game_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>twitch.live_streams_view.stream_type_id</code>.
     */
    public final TableField<LiveStreamsViewRecord, Integer> STREAM_TYPE_ID = createField("stream_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>twitch.live_streams_view.language_id</code>.
     */
    public final TableField<LiveStreamsViewRecord, Integer> LANGUAGE_ID = createField("language_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>twitch.live_streams_view</code> table reference
     */
    public LiveStreamsView() {
        this(DSL.name("live_streams_view"), null);
    }

    /**
     * Create an aliased <code>twitch.live_streams_view</code> table reference
     */
    public LiveStreamsView(String alias) {
        this(DSL.name(alias), LIVE_STREAMS_VIEW);
    }

    /**
     * Create an aliased <code>twitch.live_streams_view</code> table reference
     */
    public LiveStreamsView(Name alias) {
        this(alias, LIVE_STREAMS_VIEW);
    }

    private LiveStreamsView(Name alias, Table<LiveStreamsViewRecord> aliased) {
        this(alias, aliased, null);
    }

    private LiveStreamsView(Name alias, Table<LiveStreamsViewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "VIEW");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Twitch.TWITCH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveStreamsView as(String alias) {
        return new LiveStreamsView(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveStreamsView as(Name alias) {
        return new LiveStreamsView(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public LiveStreamsView rename(String name) {
        return new LiveStreamsView(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LiveStreamsView rename(Name name) {
        return new LiveStreamsView(name, null);
    }
}
