/*
 * This file is generated by jOOQ.
*/
package twitch.explorer.database.jooq.db.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import twitch.explorer.database.jooq.db.Twitch;
import twitch.explorer.database.jooq.db.tables.records.NewViewRecord;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NewView extends TableImpl<NewViewRecord> {

    private static final long serialVersionUID = -321169462;

    /**
     * The reference instance of <code>twitch.new_view</code>
     */
    public static final NewView NEW_VIEW = new NewView();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NewViewRecord> getRecordType() {
        return NewViewRecord.class;
    }

    /**
     * The column <code>twitch.new_view.max-fetched</code>.
     */
    public final TableField<NewViewRecord, Timestamp> MAX_FETCHED = createField("max-fetched", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>twitch.new_view.user_id</code>.
     */
    public final TableField<NewViewRecord, Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>twitch.new_view</code> table reference
     */
    public NewView() {
        this(DSL.name("new_view"), null);
    }

    /**
     * Create an aliased <code>twitch.new_view</code> table reference
     */
    public NewView(String alias) {
        this(DSL.name(alias), NEW_VIEW);
    }

    /**
     * Create an aliased <code>twitch.new_view</code> table reference
     */
    public NewView(Name alias) {
        this(alias, NEW_VIEW);
    }

    private NewView(Name alias, Table<NewViewRecord> aliased) {
        this(alias, aliased, null);
    }

    private NewView(Name alias, Table<NewViewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "VIEW");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Twitch.TWITCH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewView as(String alias) {
        return new NewView(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewView as(Name alias) {
        return new NewView(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public NewView rename(String name) {
        return new NewView(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NewView rename(Name name) {
        return new NewView(name, null);
    }
}
