/*
 * This file is generated by jOOQ.
*/
package twitch.explorer.database.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import twitch.explorer.database.jooq.db.Indexes;
import twitch.explorer.database.jooq.db.Keys;
import twitch.explorer.database.jooq.db.Twitch;
import twitch.explorer.database.jooq.db.tables.records.StreamCommunityRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StreamCommunity extends TableImpl<StreamCommunityRecord> {

    private static final long serialVersionUID = -509753674;

    /**
     * The reference instance of <code>twitch.stream_community</code>
     */
    public static final StreamCommunity STREAM_COMMUNITY = new StreamCommunity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StreamCommunityRecord> getRecordType() {
        return StreamCommunityRecord.class;
    }

    /**
     * The column <code>twitch.stream_community.stream_id</code>.
     */
    public final TableField<StreamCommunityRecord, Double> STREAM_ID = createField("stream_id", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>twitch.stream_community.community_id</code>.
     */
    public final TableField<StreamCommunityRecord, Integer> COMMUNITY_ID = createField("community_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>twitch.stream_community</code> table reference
     */
    public StreamCommunity() {
        this(DSL.name("stream_community"), null);
    }

    /**
     * Create an aliased <code>twitch.stream_community</code> table reference
     */
    public StreamCommunity(String alias) {
        this(DSL.name(alias), STREAM_COMMUNITY);
    }

    /**
     * Create an aliased <code>twitch.stream_community</code> table reference
     */
    public StreamCommunity(Name alias) {
        this(alias, STREAM_COMMUNITY);
    }

    private StreamCommunity(Name alias, Table<StreamCommunityRecord> aliased) {
        this(alias, aliased, null);
    }

    private StreamCommunity(Name alias, Table<StreamCommunityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Twitch.TWITCH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.STREAM_COMMUNITY_COMMUNITY_ID_FK_IDX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<StreamCommunityRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<StreamCommunityRecord, ?>>asList(Keys.FK_STREAM_COMMUNITY_COMMUNITY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StreamCommunity as(String alias) {
        return new StreamCommunity(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StreamCommunity as(Name alias) {
        return new StreamCommunity(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StreamCommunity rename(String name) {
        return new StreamCommunity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StreamCommunity rename(Name name) {
        return new StreamCommunity(name, null);
    }
}
