/*
 * This file is generated by jOOQ.
*/
package twitch.explorer.database.jooq.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;

import twitch.explorer.database.jooq.db.tables.GamesLive;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GamesLiveRecord extends TableRecordImpl<GamesLiveRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = -350900148;

    /**
     * Setter for <code>twitch.games_live.game_id</code>.
     */
    public void setGameId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>twitch.games_live.game_id</code>.
     */
    public Integer getGameId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>twitch.games_live.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>twitch.games_live.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>twitch.games_live.art_url</code>.
     */
    public void setArtUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>twitch.games_live.art_url</code>.
     */
    public String getArtUrl() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return GamesLive.GAMES_LIVE.GAME_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return GamesLive.GAMES_LIVE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return GamesLive.GAMES_LIVE.ART_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getGameId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getArtUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getGameId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getArtUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GamesLiveRecord value1(Integer value) {
        setGameId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GamesLiveRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GamesLiveRecord value3(String value) {
        setArtUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GamesLiveRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GamesLiveRecord
     */
    public GamesLiveRecord() {
        super(GamesLive.GAMES_LIVE);
    }

    /**
     * Create a detached, initialised GamesLiveRecord
     */
    public GamesLiveRecord(Integer gameId, String name, String artUrl) {
        super(GamesLive.GAMES_LIVE);

        set(0, gameId);
        set(1, name);
        set(2, artUrl);
    }
}
