/*
 * This file is generated by jOOQ.
*/
package twitch.explorer.database.jooq.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;

import twitch.explorer.database.jooq.db.tables.LatestFollowersUpdateView;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LatestFollowersUpdateViewRecord extends TableRecordImpl<LatestFollowersUpdateViewRecord> implements Record4<Integer, Integer, Timestamp, Long> {

    private static final long serialVersionUID = -86632747;

    /**
     * Setter for <code>twitch.latest_followers_update_view.followers_id</code>.
     */
    public void setFollowersId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>twitch.latest_followers_update_view.followers_id</code>.
     */
    public Integer getFollowersId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>twitch.latest_followers_update_view.followers</code>.
     */
    public void setFollowers(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>twitch.latest_followers_update_view.followers</code>.
     */
    public Integer getFollowers() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>twitch.latest_followers_update_view.fetched</code>.
     */
    public void setFetched(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>twitch.latest_followers_update_view.fetched</code>.
     */
    public Timestamp getFetched() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>twitch.latest_followers_update_view.user_id</code>.
     */
    public void setUserId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>twitch.latest_followers_update_view.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Timestamp, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Timestamp, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return LatestFollowersUpdateView.LATEST_FOLLOWERS_UPDATE_VIEW.FOLLOWERS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return LatestFollowersUpdateView.LATEST_FOLLOWERS_UPDATE_VIEW.FOLLOWERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return LatestFollowersUpdateView.LATEST_FOLLOWERS_UPDATE_VIEW.FETCHED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return LatestFollowersUpdateView.LATEST_FOLLOWERS_UPDATE_VIEW.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getFollowersId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getFollowers();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getFetched();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getFollowersId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getFollowers();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getFetched();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LatestFollowersUpdateViewRecord value1(Integer value) {
        setFollowersId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LatestFollowersUpdateViewRecord value2(Integer value) {
        setFollowers(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LatestFollowersUpdateViewRecord value3(Timestamp value) {
        setFetched(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LatestFollowersUpdateViewRecord value4(Long value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LatestFollowersUpdateViewRecord values(Integer value1, Integer value2, Timestamp value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LatestFollowersUpdateViewRecord
     */
    public LatestFollowersUpdateViewRecord() {
        super(LatestFollowersUpdateView.LATEST_FOLLOWERS_UPDATE_VIEW);
    }

    /**
     * Create a detached, initialised LatestFollowersUpdateViewRecord
     */
    public LatestFollowersUpdateViewRecord(Integer followersId, Integer followers, Timestamp fetched, Long userId) {
        super(LatestFollowersUpdateView.LATEST_FOLLOWERS_UPDATE_VIEW);

        set(0, followersId);
        set(1, followers);
        set(2, fetched);
        set(3, userId);
    }
}
