/*
 * This file is generated by jOOQ.
*/
package twitch.explorer.database.jooq.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;

import twitch.explorer.database.jooq.db.tables.LiveStreamsView;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LiveStreamsViewRecord extends TableRecordImpl<LiveStreamsViewRecord> implements Record10<Long, String, Timestamp, Timestamp, String, Integer, Long, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1955175795;

    /**
     * Setter for <code>twitch.live_streams_view.stream_id</code>.
     */
    public void setStreamId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>twitch.live_streams_view.stream_id</code>.
     */
    public Long getStreamId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>twitch.live_streams_view.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>twitch.live_streams_view.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>twitch.live_streams_view.started</code>.
     */
    public void setStarted(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>twitch.live_streams_view.started</code>.
     */
    public Timestamp getStarted() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>twitch.live_streams_view.ended</code>.
     */
    public void setEnded(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>twitch.live_streams_view.ended</code>.
     */
    public Timestamp getEnded() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>twitch.live_streams_view.thumbnail</code>.
     */
    public void setThumbnail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>twitch.live_streams_view.thumbnail</code>.
     */
    public String getThumbnail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>twitch.live_streams_view.view_count</code>. latest read view count
     */
    public void setViewCount(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>twitch.live_streams_view.view_count</code>. latest read view count
     */
    public Integer getViewCount() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>twitch.live_streams_view.user_id</code>.
     */
    public void setUserId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>twitch.live_streams_view.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>twitch.live_streams_view.game_id</code>.
     */
    public void setGameId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>twitch.live_streams_view.game_id</code>.
     */
    public Integer getGameId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>twitch.live_streams_view.stream_type_id</code>.
     */
    public void setStreamTypeId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>twitch.live_streams_view.stream_type_id</code>.
     */
    public Integer getStreamTypeId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>twitch.live_streams_view.language_id</code>.
     */
    public void setLanguageId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>twitch.live_streams_view.language_id</code>.
     */
    public Integer getLanguageId() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, String, Timestamp, Timestamp, String, Integer, Long, Integer, Integer, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, String, Timestamp, Timestamp, String, Integer, Long, Integer, Integer, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return LiveStreamsView.LIVE_STREAMS_VIEW.STREAM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return LiveStreamsView.LIVE_STREAMS_VIEW.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return LiveStreamsView.LIVE_STREAMS_VIEW.STARTED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return LiveStreamsView.LIVE_STREAMS_VIEW.ENDED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return LiveStreamsView.LIVE_STREAMS_VIEW.THUMBNAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return LiveStreamsView.LIVE_STREAMS_VIEW.VIEW_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return LiveStreamsView.LIVE_STREAMS_VIEW.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return LiveStreamsView.LIVE_STREAMS_VIEW.GAME_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return LiveStreamsView.LIVE_STREAMS_VIEW.STREAM_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return LiveStreamsView.LIVE_STREAMS_VIEW.LANGUAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getStreamId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getStarted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getEnded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getThumbnail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getViewCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getGameId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getStreamTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getLanguageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getStreamId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getStarted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getEnded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getThumbnail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getViewCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getGameId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getStreamTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getLanguageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveStreamsViewRecord value1(Long value) {
        setStreamId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveStreamsViewRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveStreamsViewRecord value3(Timestamp value) {
        setStarted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveStreamsViewRecord value4(Timestamp value) {
        setEnded(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveStreamsViewRecord value5(String value) {
        setThumbnail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveStreamsViewRecord value6(Integer value) {
        setViewCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveStreamsViewRecord value7(Long value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveStreamsViewRecord value8(Integer value) {
        setGameId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveStreamsViewRecord value9(Integer value) {
        setStreamTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveStreamsViewRecord value10(Integer value) {
        setLanguageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveStreamsViewRecord values(Long value1, String value2, Timestamp value3, Timestamp value4, String value5, Integer value6, Long value7, Integer value8, Integer value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LiveStreamsViewRecord
     */
    public LiveStreamsViewRecord() {
        super(LiveStreamsView.LIVE_STREAMS_VIEW);
    }

    /**
     * Create a detached, initialised LiveStreamsViewRecord
     */
    public LiveStreamsViewRecord(Long streamId, String title, Timestamp started, Timestamp ended, String thumbnail, Integer viewCount, Long userId, Integer gameId, Integer streamTypeId, Integer languageId) {
        super(LiveStreamsView.LIVE_STREAMS_VIEW);

        set(0, streamId);
        set(1, title);
        set(2, started);
        set(3, ended);
        set(4, thumbnail);
        set(5, viewCount);
        set(6, userId);
        set(7, gameId);
        set(8, streamTypeId);
        set(9, languageId);
    }
}
