/*
 * This file is generated by jOOQ.
*/
package twitch.explorer.database.jooq.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;

import twitch.explorer.database.jooq.db.tables.LiveLongestTimeSinceFollowerUpdateView;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LiveLongestTimeSinceFollowerUpdateViewRecord extends TableRecordImpl<LiveLongestTimeSinceFollowerUpdateViewRecord> implements Record9<Long, String, Timestamp, String, Integer, Long, Integer, Integer, Timestamp> {

    private static final long serialVersionUID = -549693167;

    /**
     * Setter for <code>twitch.live_longest_time_since_follower_update_view.stream_id</code>.
     */
    public void setStreamId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>twitch.live_longest_time_since_follower_update_view.stream_id</code>.
     */
    public Long getStreamId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>twitch.live_longest_time_since_follower_update_view.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>twitch.live_longest_time_since_follower_update_view.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>twitch.live_longest_time_since_follower_update_view.started</code>.
     */
    public void setStarted(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>twitch.live_longest_time_since_follower_update_view.started</code>.
     */
    public Timestamp getStarted() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>twitch.live_longest_time_since_follower_update_view.thumbnail</code>.
     */
    public void setThumbnail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>twitch.live_longest_time_since_follower_update_view.thumbnail</code>.
     */
    public String getThumbnail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>twitch.live_longest_time_since_follower_update_view.view_count</code>. latest read view count
     */
    public void setViewCount(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>twitch.live_longest_time_since_follower_update_view.view_count</code>. latest read view count
     */
    public Integer getViewCount() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>twitch.live_longest_time_since_follower_update_view.user_id</code>.
     */
    public void setUserId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>twitch.live_longest_time_since_follower_update_view.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>twitch.live_longest_time_since_follower_update_view.game_id</code>.
     */
    public void setGameId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>twitch.live_longest_time_since_follower_update_view.game_id</code>.
     */
    public Integer getGameId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>twitch.live_longest_time_since_follower_update_view.followers</code>.
     */
    public void setFollowers(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>twitch.live_longest_time_since_follower_update_view.followers</code>.
     */
    public Integer getFollowers() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>twitch.live_longest_time_since_follower_update_view.fetched</code>.
     */
    public void setFetched(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>twitch.live_longest_time_since_follower_update_view.fetched</code>.
     */
    public Timestamp getFetched() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, Timestamp, String, Integer, Long, Integer, Integer, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, Timestamp, String, Integer, Long, Integer, Integer, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return LiveLongestTimeSinceFollowerUpdateView.LIVE_LONGEST_TIME_SINCE_FOLLOWER_UPDATE_VIEW.STREAM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return LiveLongestTimeSinceFollowerUpdateView.LIVE_LONGEST_TIME_SINCE_FOLLOWER_UPDATE_VIEW.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return LiveLongestTimeSinceFollowerUpdateView.LIVE_LONGEST_TIME_SINCE_FOLLOWER_UPDATE_VIEW.STARTED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return LiveLongestTimeSinceFollowerUpdateView.LIVE_LONGEST_TIME_SINCE_FOLLOWER_UPDATE_VIEW.THUMBNAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return LiveLongestTimeSinceFollowerUpdateView.LIVE_LONGEST_TIME_SINCE_FOLLOWER_UPDATE_VIEW.VIEW_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return LiveLongestTimeSinceFollowerUpdateView.LIVE_LONGEST_TIME_SINCE_FOLLOWER_UPDATE_VIEW.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return LiveLongestTimeSinceFollowerUpdateView.LIVE_LONGEST_TIME_SINCE_FOLLOWER_UPDATE_VIEW.GAME_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return LiveLongestTimeSinceFollowerUpdateView.LIVE_LONGEST_TIME_SINCE_FOLLOWER_UPDATE_VIEW.FOLLOWERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return LiveLongestTimeSinceFollowerUpdateView.LIVE_LONGEST_TIME_SINCE_FOLLOWER_UPDATE_VIEW.FETCHED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getStreamId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getStarted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getThumbnail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getViewCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getGameId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getFollowers();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getFetched();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getStreamId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getStarted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getThumbnail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getViewCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getGameId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getFollowers();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getFetched();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveLongestTimeSinceFollowerUpdateViewRecord value1(Long value) {
        setStreamId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveLongestTimeSinceFollowerUpdateViewRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveLongestTimeSinceFollowerUpdateViewRecord value3(Timestamp value) {
        setStarted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveLongestTimeSinceFollowerUpdateViewRecord value4(String value) {
        setThumbnail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveLongestTimeSinceFollowerUpdateViewRecord value5(Integer value) {
        setViewCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveLongestTimeSinceFollowerUpdateViewRecord value6(Long value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveLongestTimeSinceFollowerUpdateViewRecord value7(Integer value) {
        setGameId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveLongestTimeSinceFollowerUpdateViewRecord value8(Integer value) {
        setFollowers(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveLongestTimeSinceFollowerUpdateViewRecord value9(Timestamp value) {
        setFetched(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveLongestTimeSinceFollowerUpdateViewRecord values(Long value1, String value2, Timestamp value3, String value4, Integer value5, Long value6, Integer value7, Integer value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LiveLongestTimeSinceFollowerUpdateViewRecord
     */
    public LiveLongestTimeSinceFollowerUpdateViewRecord() {
        super(LiveLongestTimeSinceFollowerUpdateView.LIVE_LONGEST_TIME_SINCE_FOLLOWER_UPDATE_VIEW);
    }

    /**
     * Create a detached, initialised LiveLongestTimeSinceFollowerUpdateViewRecord
     */
    public LiveLongestTimeSinceFollowerUpdateViewRecord(Long streamId, String title, Timestamp started, String thumbnail, Integer viewCount, Long userId, Integer gameId, Integer followers, Timestamp fetched) {
        super(LiveLongestTimeSinceFollowerUpdateView.LIVE_LONGEST_TIME_SINCE_FOLLOWER_UPDATE_VIEW);

        set(0, streamId);
        set(1, title);
        set(2, started);
        set(3, thumbnail);
        set(4, viewCount);
        set(5, userId);
        set(6, gameId);
        set(7, followers);
        set(8, fetched);
    }
}
