/*
 * This file is generated by jOOQ.
*/
package twitch.explorer.database.jooq.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import twitch.explorer.database.jooq.db.tables.Stream;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StreamRecord extends UpdatableRecordImpl<StreamRecord> implements Record10<Integer, String, Timestamp, Timestamp, String, String, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 2073773588;

    /**
     * Setter for <code>twitch.stream.stream_id</code>.
     */
    public void setStreamId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>twitch.stream.stream_id</code>.
     */
    public Integer getStreamId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>twitch.stream.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>twitch.stream.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>twitch.stream.started</code>.
     */
    public void setStarted(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>twitch.stream.started</code>.
     */
    public Timestamp getStarted() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>twitch.stream.ended</code>.
     */
    public void setEnded(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>twitch.stream.ended</code>.
     */
    public Timestamp getEnded() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>twitch.stream.thumbnail</code>.
     */
    public void setThumbnail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>twitch.stream.thumbnail</code>.
     */
    public String getThumbnail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>twitch.stream.view_count</code>. latest read view count
     */
    public void setViewCount(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>twitch.stream.view_count</code>. latest read view count
     */
    public String getViewCount() {
        return (String) get(5);
    }

    /**
     * Setter for <code>twitch.stream.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>twitch.stream.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>twitch.stream.game_id</code>.
     */
    public void setGameId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>twitch.stream.game_id</code>.
     */
    public Integer getGameId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>twitch.stream.stream_type_id</code>.
     */
    public void setStreamTypeId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>twitch.stream.stream_type_id</code>.
     */
    public Integer getStreamTypeId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>twitch.stream.language_id</code>.
     */
    public void setLanguageId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>twitch.stream.language_id</code>.
     */
    public Integer getLanguageId() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, Timestamp, Timestamp, String, String, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, Timestamp, Timestamp, String, String, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Stream.STREAM.STREAM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Stream.STREAM.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Stream.STREAM.STARTED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Stream.STREAM.ENDED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Stream.STREAM.THUMBNAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Stream.STREAM.VIEW_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Stream.STREAM.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Stream.STREAM.GAME_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Stream.STREAM.STREAM_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Stream.STREAM.LANGUAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getStreamId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getStarted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getEnded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getThumbnail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getViewCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getGameId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getStreamTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getLanguageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getStreamId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getStarted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getEnded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getThumbnail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getViewCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getGameId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getStreamTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getLanguageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StreamRecord value1(Integer value) {
        setStreamId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StreamRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StreamRecord value3(Timestamp value) {
        setStarted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StreamRecord value4(Timestamp value) {
        setEnded(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StreamRecord value5(String value) {
        setThumbnail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StreamRecord value6(String value) {
        setViewCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StreamRecord value7(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StreamRecord value8(Integer value) {
        setGameId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StreamRecord value9(Integer value) {
        setStreamTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StreamRecord value10(Integer value) {
        setLanguageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StreamRecord values(Integer value1, String value2, Timestamp value3, Timestamp value4, String value5, String value6, Integer value7, Integer value8, Integer value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StreamRecord
     */
    public StreamRecord() {
        super(Stream.STREAM);
    }

    /**
     * Create a detached, initialised StreamRecord
     */
    public StreamRecord(Integer streamId, String title, Timestamp started, Timestamp ended, String thumbnail, String viewCount, Integer userId, Integer gameId, Integer streamTypeId, Integer languageId) {
        super(Stream.STREAM);

        set(0, streamId);
        set(1, title);
        set(2, started);
        set(3, ended);
        set(4, thumbnail);
        set(5, viewCount);
        set(6, userId);
        set(7, gameId);
        set(8, streamTypeId);
        set(9, languageId);
    }
}
