/*
 * This file is generated by jOOQ.
*/
package twitch.explorer.database.jooq.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import twitch.explorer.database.jooq.db.tables.UserType;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserTypeRecord extends UpdatableRecordImpl<UserTypeRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -1127950192;

    /**
     * Setter for <code>twitch.user_type.user_type_id</code>.
     */
    public void setUserTypeId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>twitch.user_type.user_type_id</code>.
     */
    public Integer getUserTypeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>twitch.user_type.type</code>. Current known users are User’s type: "staff", "admin", "global_mod", or "".
More info at https://dev.twitch.tv/docs/api/reference#get-users

     */
    public void setType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>twitch.user_type.type</code>. Current known users are User’s type: "staff", "admin", "global_mod", or "".
More info at https://dev.twitch.tv/docs/api/reference#get-users

     */
    public String getType() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserType.USER_TYPE.USER_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return UserType.USER_TYPE.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getUserTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserTypeRecord value1(Integer value) {
        setUserTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserTypeRecord value2(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserTypeRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserTypeRecord
     */
    public UserTypeRecord() {
        super(UserType.USER_TYPE);
    }

    /**
     * Create a detached, initialised UserTypeRecord
     */
    public UserTypeRecord(Integer userTypeId, String type) {
        super(UserType.USER_TYPE);

        set(0, userTypeId);
        set(1, type);
    }
}
